# Generated by Django 2.2.23 on 2021-12-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210829_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpolluser',
            name='language',
            field=models.CharField(choices=[('german', 'German'), ('english', 'English')], default='german', max_length=20),
        ),
    ]
