# Generated by Django 2.2.23 on 2021-08-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0018_poll_change_vote_after_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='require_login_view',
            field=models.BooleanField(default=False),
        ),
    ]
