# Generated by Django 2.2.23 on 2021-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_poll_require_login_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='anonymous_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='change_vote_after_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='require_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='require_login_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sorting',
            field=models.IntegerField(default=2),
        ),
    ]
