# Generated by Django 2.2.28 on 2023-01-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0020_auto_20211106_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="separate_groups",
            field=models.BooleanField(default=False),
        ),
    ]
